In [ ]:
import cv2
import numpy as np


In [6]:
import cv2
import numpy as np

Img = cv2.imread("MenOne.jpeg")
re_Img = cv2.resize(Img, (500,600))
cv2.imshow("MenFrame" , re_Img)
cv2.waitKey(0)
cv2.destroyAllWindows

<function destroyAllWindows>

In [10]:
import numpy as np

v = np.array([[1,2,1,2],
            [1,2,1,2]])
v

array([[1, 2, 1, 2],
       [1, 2, 1, 2]])

In [11]:
import cv2
import numpy as np

Img = cv2.imread("MenOne.jpeg")

print(Img)



[[[184 179 181]
  [184 179 181]
  [184 179 181]
  ...
  [193 188 189]
  [193 188 189]
  [193 188 189]]

 [[184 179 181]
  [184 179 181]
  [184 179 181]
  ...
  [194 189 190]
  [194 189 190]
  [194 189 190]]

 [[184 179 181]
  [184 179 181]
  [184 179 181]
  ...
  [194 189 190]
  [194 189 190]
  [194 189 190]]

 ...

 [[183 180 182]
  [183 180 182]
  [183 180 182]
  ...
  [184 179 181]
  [184 179 181]
  [184 179 181]]

 [[187 182 184]
  [186 181 183]
  [186 181 183]
  ...
  [184 179 181]
  [183 178 180]
  [183 178 180]]

 [[187 182 184]
  [186 181 183]
  [186 181 183]
  ...
  [184 179 181]
  [183 178 180]
  [183 178 180]]]
